import Head from "next/head";
import { useEffect } from "react";
import { createContext, useContext } from "react";
import styles from "@/styles/Home.module.css";
import Navbar from "@/components/Navbar";

export const GeneralContext = createContext({
  user: {
    name: "Marina",
    surname: "Valenza",
    age: 31,
  },
});

export default function Home() {
  const context = useContext(GeneralContext);

  useEffect(() => {
    fetch("api/hello", {
      method: "GET",
    })
      .then((res) => res.json())
      .then((data) => data);
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
        <div>Hello {context.user.name} </div>
        <Navbar />
      </main>
    </>
  );
}
